### ISSUE TITLE
Usage Example slots are not working

### ISSUE THREAD

**Issue by abraxa1982** [michaelKaefer/oauth2-amazon#1]
Hi, 

when you want to change the scope and not use the standard, you need to change the `$options = ['profile', 'postal_code', 'payments:widget', 'payments:shipping_address', 'payments:billing_address'];`
    
to 

`$options = ['scope'=>'profile postal_code payments:widget payments:shipping_address payments:billing_address'];`

**Comment by michaelKaefer** [comment]
@abraxa1982 Thank you! I changed the code example.
